### ISSUE TITLE
Expensive health check in area_query.cc

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#232]
Test case from #231:

```C
[out:json][timeout:300][date:"2015-06-01T00:00:00Z"];
{{geocodeArea:USA}}->.searchArea;
(
  node["exit_to"](area.searchArea);
  way["destination"]["highway"="motorway_link"](area.searchArea);
  way["destination"]["highway"="motorway"](area.searchArea);
);
out count;
```

Result:
```JSON
{
  "count": {
    "total": 34446,
    "nodes": 18313,
    "ways": 16133,
    "relations": 0,
    "areas": 0
  }
}
```

Takes about 5 minutes to run on test754.

sudo perf top shows two locations where a lot of time is spent:

```
 65.03%  libstdc++.so.6.0.19  [.] std::_Rb_tree_increment(std::_Rb_tree_node_base const*)
 30.74%  interpreter          [.] eval_map(std::map<Uint32_Index, std::vector<Node_Skeleton, std::allocator<Node_Skeleton> >, std::less<Uint32_Index>, std::allocator<std::pair<Uint
  0.96%  libc-2.19.so         [.] 0x0000000000080c2a
  0.56%  liblz4.so.1.5.0      [.] LZ4_decompress_safe
  0.45%  interpreter          [.] eval_map(std::map<Uint32_Index, std::vector<Attic<Node_Skeleton>, std::allocator<Attic<Node_Skeleton> > >, std::less<Uint32_Index>, std::allocator
  0.25%  interpreter          [.] std::vector<unsigned long long, std::allocator<unsigned long long> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned long long*, std::vector
  0.23%  interpreter          [.] Block_Backend_Basic_Iterator<Uint31_Index, Area_Block>::object()
  0.19%  libc-2.19.so         [.] malloc
  0.19%  interpreter          [.] void std::__introsort_loop<__gnu_cxx::__normal_iterator<std::pair<Uint31_Index, Uint31_Index>*, std::vector<std::pair<Uint31_Index, Uint31_Index>,
  0.16%  [kernel]             [k] copy_user_enhanced_fast_string
  0.16%  interpreter          [.] std::map<Uint31_Index, std::vector<Area_Block, std::allocator<Area_Block> >, std::less<Uint31_Index>, std::allocator<std::pair<Uint31_Index const,
  0.08%  interpreter          [.] Block_Backend_Discrete_Iterator<Uint31_Index, Area_Block, std::_Rb_tree_const_iterator<Uint31_Index> >::operator++()
  0.07%  interpreter          [.] bool std::binary_search<__gnu_cxx::__normal_iterator<Uint32_Index*, std::vector<Uint32_Index, std::allocator<Uint32_Index> > >, Uint32_Index>(__gn
  0.06%  libstdc++.so.6.0.19  [.] operator new(unsigned long)
  0.05%  interpreter          [.] void collect_items_range<Uint32_Index, Node_Skeleton, std::set<std::pair<Uint32_Index, Uint32_Index>, std::less<std::pair<Uint32_Index, Uint32_Ind
  0.04%  [kernel]             [k] find_get_page
```

Stack trace:

```
#0  eval_map (nodes=...) at ../src/overpass_api/dispatch/resource_manager.cc:62
#1  0x00000000005f922e in eval_set (set_=...) at ../src/overpass_api/dispatch/resource_manager.cc:129
#2  0x00000000005f9499 in Resource_Manager::health_check (this=this@entry=0x44546d0, stmt=..., extra_time=extra_time@entry=0, extra_space=extra_space@entry=0)
    at ../src/overpass_api/dispatch/resource_manager.cc:198
#3  0x000000000042e855 in Area_Query_Statement::collect_nodes<Attic<Node_Skeleton> > (this=0x60433d0, nodes=..., req=..., add_border=add_border@entry=false, rman=...)
    at ../../src/test-bin/../overpass_api/statements/area_query.cc:406
#4  0x0000000000418a61 in Area_Constraint::filter (this=<optimized out>, query=..., rman=..., into=..., timestamp=135262240768)
    at ../../src/test-bin/../overpass_api/statements/area_query.cc:170
#5  0x00000000004fb38e in Query_Statement::execute (this=0x4b54020, rman=...) at ../../src/test-bin/../overpass_api/statements/query.cc:1592
#6  0x00000000005723c3 in Union_Statement::execute (this=0x612a640, rman=...) at ../../src/test-bin/../overpass_api/statements/union.cc:73
#7  0x00000000004b1bd1 in Osm_Script_Statement::execute (this=0x6320350, rman=...) at ../../src/test-bin/../overpass_api/statements/osm_script.cc:397
```

Expensive statement:
```C
 rman.health_check(*this);
--> 
resource_manager.cc:
      size += eval_set(it->second);

```

Relevant locations in area_query.cc:

* Line 406: Area_Query_Statement::collect_nodes
* Line 682: Area_Query_Statement::collect_ways

Without the health check, the runtime drops from 5 minutes down to 27s.

Question: can this expensive health check be somehow avoided, or reduced in scope so that `eval_set` will not be called so frequently (or at all?)

**Comment by drolbr** [comment]
Fixed in commit baea969fdaf7fd2bad08a06ef9873679116903f6
