### ISSUE TITLE
Way_Skeleton: reduce size of nds

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#248]
Today, each node is stored as 64 bit value, which amounts to about 30GB of uncompressed data for a current planet file. Similar to the [PBF format](http://wiki.openstreetmap.org/wiki/PBF_Format), these nodes could be stored as varints using delta coding, which brings down the size to 7 GB (uncompressed).

The basic idea here is that node ids for an OSM way are frequently very close to each other. When only storing the delta value and applying additional varint encoding, small values could allocate as little as 1-2 bytes instead of 8 bytes.

* More details on encoding: https://developers.google.com/protocol-buffers/docs/encoding?hl=en

* Relevant parts from Google Protocol Buffers:

  - WireFormatLite::ZigZagEncode64
  - WireFormatLite::ZigZagDecode64
  - CodedOutputStream::WriteVarint64ToArrayInline
  - CodedInputStream::ReadVarint64Fallback
  - CodedOutputStream::VarintSize64

Working prototype is included in branch: https://github.com/mmd-osm/Overpass-API/tree/test_way_diffs, patch against v0.7.52 in branch: https://github.com/mmd-osm/Overpass-API/tree/patch_issue_248

Performance impact seems to be not too bad (single percentage), compression is still more expensive.

**Comment by mmd-osm** [comment]
Running a swiss extract via update_database, the Reorg Database step now crashes in `merge_files`, probably due to the more compact layout of ways in a buffer. I guess this is unrelated to the prototype above and simply a side effect, which wasn't uncovered so far?

Compile using:
```
configure CXXFLAGS="-O3 -ggdb -fno-omit-frame-pointer -fsanitize=address"
```


```
==18443== ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fbe46152806 at pc 0x5f0c89 bp 0x7ffde666e9b0 sp 0x7ffde666e9a8
READ of size 4 at 0x7fbe46152806 thread T0
    #0 0x5f0c88 in _ZN12Way_SkeletonC2EPv {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../core/type_way.h:128
    #1 0x6b8276 in _ZN13Block_BackendI12Uint31_Index12Way_SkeletonSt23_Rb_tree_const_iteratorIS0_EE12update_groupI19Empty_Update_LoggerIS0_S1_EEEvR29File_Blocks_Discrete_IteratorIS0_S3_ERKSt3mapIS0_St3setIS1_St4lessIS1_ESaIS1_EESD_IS0_ESaISt4pairIKS0_SG_EEESO_RT_ {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/block_backend.h:1085
    #2 0x6bbd94 in _ZN13Block_BackendI12Uint31_Index12Way_SkeletonSt23_Rb_tree_const_iteratorIS0_EE6updateI19Empty_Update_LoggerIS0_S1_EEEvRKSt3mapIS0_St3setIS1_St4lessIS1_ESaIS1_EESA_IS0_ESaISt4pairIKS0_SD_EEESL_RT_ {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/block_backend.h:754
    #3 0x6bd292 in _ZN13Block_BackendI12Uint31_Index12Way_SkeletonSt23_Rb_tree_const_iteratorIS0_EE6updateERKSt3mapIS0_St3setIS1_St4lessIS1_ESaIS1_EES7_IS0_ESaISt4pairIKS0_SA_EEESI_ {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/block_backend.h:231
    #4 0x5daae3 in _ZN11Way_Updater11merge_filesERKSt6vectorISsSaISsEESs {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/way_updater.cc:1117 (discriminator 1)
    #5 0x5e5114 in _ZN11Way_Updater6updateEP20Osm_Backend_CallbackbRKSt3mapI12Uint31_IndexSt3setI13Node_SkeletonSt4lessIS5_ESaIS5_EES6_IS3_ESaISt4pairIKS3_S9_EEESH_RKS2_IS3_S4_I5AtticIS5_ES6_ISJ_ESaISJ_EESA_SaISB_ISC_SM_EEE {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/way_updater.cc:1046 (discriminator 1)
    #6 0x78a550 in relation_start {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/osm_updater.cc:295 (discriminator 3)
    #7 0x78ad67 in _Z5startPKcPS0_ {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/osm_updater.cc:410
    #8 0x7fbe4779094e in ?? ??:0
    #9 0x7fbe4779164d in ?? ??:0
    #10 0x7fbe477935de in XML_ParseBuffer ??:?
    #11 0x800126 in _Z5parseP8_IO_FILEPFvPKcPS2_EPFvS2_EPFvPvS2_iE {home}/osm-3s-patch-version/build/../src/expat/expat_justparse_interface.cc:101
    #12 0x78e8a4 in _ZN11Osm_Updater21parse_file_completelyEP8_IO_FILE {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/osm_updater.cc:497
    #13 0x405b5d in main {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/update_database.cc:115
    #14 0x7fbe46ec8ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #15 0x406c43 in _start ??:?
0x7fbe46152806 is located 6 bytes to the right of 524288-byte region [0x7fbe460d2800,0x7fbe46152800)
allocated by thread T0 here:
    #0 0x7fbe47ffa41a in malloc ??:?
    #1 0x6b7882 in Void_Pointer {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/types.h:134
    #2 0x6bbd94 in _ZN13Block_BackendI12Uint31_Index12Way_SkeletonSt23_Rb_tree_const_iteratorIS0_EE6updateI19Empty_Update_LoggerIS0_S1_EEEvRKSt3mapIS0_St3setIS1_St4lessIS1_ESaIS1_EESA_IS0_ESaISt4pairIKS0_SD_EEESL_RT_ {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/block_backend.h:754
    #3 0x6bd292 in _ZN13Block_BackendI12Uint31_Index12Way_SkeletonSt23_Rb_tree_const_iteratorIS0_EE6updateERKSt3mapIS0_St3setIS1_St4lessIS1_ESaIS1_EES7_IS0_ESaISt4pairIKS0_SA_EEESI_ {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/../../template_db/block_backend.h:231
    #4 0x5daae3 in _ZN11Way_Updater11merge_filesERKSt6vectorISsSaISsEESs {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/way_updater.cc:1117 (discriminator 1)
    #5 0x5e5114 in _ZN11Way_Updater6updateEP20Osm_Backend_CallbackbRKSt3mapI12Uint31_IndexSt3setI13Node_SkeletonSt4lessIS5_ESaIS5_EES6_IS3_ESaISt4pairIKS3_S9_EEESH_RKS2_IS3_S4_I5AtticIS5_ES6_ISJ_ESaISJ_EESA_SaISB_ISC_SM_EEE {home}/osm-3s-patch-version/build/test-bin/../../src/test-bin/../overpass_api/osm-backend/way_updater.cc:1046 (discriminator 1)
    #6 0x78a550 in relation_start {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/osm_updater.cc:295 (discriminator 3)
    #7 0x78ad67 in _Z5startPKcPS0_ {home}/osm-3s-patch-version/build/../src/overpass_api/osm-backend/osm_updater.cc:410
    #8 0x7fbe4779094e in ?? ??:0
Shadow bytes around the buggy address:
  0x0ff848c224b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff848c224c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff848c224d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff848c224e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff848c224f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff848c22500:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff848c22510: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff848c22520: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff848c22530: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff848c22540: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff848c22550: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==18443== ABORTING
```

**Comment by mmd-osm** [comment]
Impact on Area creation (full) - w/o patch: 6,5 hours, including this patch: 4,5 hours.
