### ISSUE TITLE
Statement dump: crashes on out_csv_finetuning

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#354]
Calling osm3s_query with `--dump-xml`, `--dump-pretty-map-ql` or `--dump-compact-map-ql` triggers various different segmentation faults due to missing NULL handling of *lhs* / *rhs* in many `dump_xml` and `dump_compact_ql` methods. Affects at least unary_operators, binary_operators, and many others.

Test on https://github.com/drolbr/Overpass-API/commit/abd1d7fe233c70b405b6e9abf0fd49bed1410487

Example:

```
way(if:!ount(members)>1000)(53.97,26.98,54.03,27.39);
out center;
```

```
#0  Evaluator_Prefix_Operator_Syntax<Evaluator_Not>::dump_xml (this=0x2edd4f0, indent=...)
    at ../../src/test-bin/../overpass_api/statements/unary_operators.h:101
#1  0x000000000063270c in Evaluator_Pair_Operator_Syntax<Evaluator_Greater>::dump_xml (this=this@entry=0x2edc9a0, indent=...)
    at ../../src/test-bin/../overpass_api/statements/binary_operators.h:110
#2  0x0000000000fdb3c9 in Statement_Dump::Factory::create_statement (this=this@entry=0x7ffe21de0290, tree_it=..., 
    tree_context=tree_context@entry=Statement::evaluator_expected) at ../src/overpass_api/statements/statement_dump.cc:1030
#3  0x0000000000f5459d in parse_value_tree<Statement_Dump> (parenthesis_expected=true, tree_context=Statement::evaluator_expected, 
    error_output=0x2edb8f0, token=..., stmt_factory=...) at ../../src/test-bin/../overpass_api/frontend/map_ql_parser.cc:660
#4  parse_query<Statement_Dump> (stmt_factory=..., parsed_query=..., type=..., from=..., token=..., 
    error_output=error_output@entry=0x2edb8f0) at ../../src/test-bin/../overpass_api/frontend/map_ql_parser.cc:1204
#5  0x0000000000f681d7 in parse_statement<Statement_Dump> (depth=0, error_output=<optimised out>, token=..., parsed_query=..., 
    stmt_factory=...) at ../../src/test-bin/../overpass_api/frontend/map_ql_parser.cc:1421
#6  generic_parse_and_validate_map_ql<Statement_Dump> (stmt_factory=..., xml_raw=..., error_output=error_output@entry=0x2edb8f0, 
    stmt_seq=std::vector of length 0, capacity 0, parsed_query=...)
    at ../../src/test-bin/../overpass_api/frontend/map_ql_parser.cc:1462
#7  0x0000000000ee5d2a in parse_and_dump_compact_from_map_ql (stmt_factory_=..., xml_raw=..., 
    error_output=error_output@entry=0x2edb8f0, parsed_query=...)
    at ../../src/test-bin/../overpass_api/frontend/map_ql_parser.cc:1500
#8  0x0000000000ec36a3 in parse_and_validate (stmt_factory=..., parsed_query=..., xml_raw=..., 
    error_output=error_output@entry=0x2edb8f0, debug_level=debug_level@entry=parser_dump_compact_map_ql)
    at ../../src/test-bin/../overpass_api/dispatch/scripting_core.cc:223
#9  0x000000000040c95c in main (argc=<optimised out>, argv=<optimised out>) at ../src/overpass_api/dispatch/osm3s_query.cc:144

```

Credits to [american fuzzy lop](http://lcamtuf.coredump.cx/afl/)

**Comment by drolbr** [comment]
Fixed.
