### ISSUE TITLE
Expensive health check in area creation full run (new_feat)

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#414]
I tested a full area creation and noticed that some parts of the processing spend a rather large amount of time in health checks (~75%), this time triggered by foreach --> Runtime_Stack_Frame::union_inward --> eval_set --> eval_map. 

Is this something we can turn off altogether for area creation?

Code based on new_features branch commit https://github.com/drolbr/Overpass-API/commit/2e95d9149d42ae1fa4d26d8962c10483833da574

From area rules file

 ```XML
<foreach into="pivot">
  <union>
    <recurse type="relation-way" from="pivot"/>
    <recurse type="way-node"/>
  </union>
  <make-area pivot="pivot"/>
</foreach>
 ```

 ```
#0  0x00007fdfc0ba2b67 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000068a4da in operator++ (this=<synthetic pointer>) at /usr/include/c++/4.8/bits/stl_tree.h:270
#2  eval_map (areas=...) at ../src/overpass_api/dispatch/resource_manager.cc:90
#3  0x000000000068a552 in eval_set (set_=...) at ../src/overpass_api/dispatch/resource_manager.cc:101
#4  0x000000000068d2ed in Runtime_Stack_Frame::union_inward (this=0x233be30, top_set_name=..., inner_set_name=...) at ../src/overpass_api/dispatch/resource_manager.cc:195
#5  0x000000000068d322 in Resource_Manager::union_inward (this=this@entry=0x233bce0, top_set_name=..., inner_set_name=...) at ../src/overpass_api/dispatch/resource_manager.cc:372
#6  0x00000000004c2a53 in Foreach_Statement::execute (this=0x200b920, rman=...) at ../src/overpass_api/statements/foreach.cc:160
#7  0x00000000004e82a0 in Osm_Script_Statement::execute (this=0x200a470, rman=...) at ../src/overpass_api/statements/osm_script.cc:256
#8  0x000000000040ca42 in main (argc=<optimized out>, argv=<optimized out>) at ../src/overpass_api/dispatch/osm3s_query.cc:233
 ```

 ```
+  58.15%  osm3s_query  libstdc++.so.6.0.19  [.] std::_Rb_tree_increment(std::_Rb_tree_node_base const*)
+  14.25%  osm3s_query  osm3s_query          [.] eval_map(std::map<Uint31_Index, std::vector<Area_Skeleton, std::allocator<Area_Skeleton> >, std::less<Uint31_Index>, std::allocator<std::pair<Uint31_Index co
+   8.44%  osm3s_query  liblz4.so.1.5.0      [.] LZ4_decompress_safe
+   5.78%  osm3s_query  libc-2.19.so         [.] 0x000000000007fdc8
+   2.78%  osm3s_query  osm3s_query          [.] File_Blocks_Discrete_Iterator<Uint31_Index, __gnu_cxx::__normal_iterator<Uint31_Index const*, std::vector<Uint31_Index, std::allocator<Uint31_Index> > > >::f
+   2.73%  osm3s_query  osm3s_query          [.] File_Blocks_Range_Iterator<Uint32_Index, Default_Range_Iterator<Uint32_Index> >::find_next_block()
+   0.83%  osm3s_query  libc-2.19.so         [.] malloc
+   0.81%  osm3s_query  [kernel.kallsyms]    [k] copy_user_enhanced_fast_string
+   0.40%  osm3s_query  osm3s_query          [.] bool std::binary_search<__gnu_cxx::__normal_iterator<Uint64 const*, std::vector<Uint64, std::allocator<Uint64> > >, Uint64>(__gnu_cxx::__normal_iterator<Uint
+   0.30%  osm3s_query  libstdc++.so.6.0.19  [.] operator new(unsigned long)
+   0.29%  osm3s_query  libstdc++.so.6.0.19  [.] 0x000000000005b6b1
+   0.28%  osm3s_query  libc-2.19.so         [.] free
+   0.23%  osm3s_query  osm3s_query          [.] void collect_items_range<Uint32_Index, Node_Skeleton, std::set<std::pair<Uint32_Index, Uint32_Index>, std::less<std::pair<Uint32_Index, Uint32_Index> >, std:
+   0.23%  osm3s_query  osm3s_query          [.] Block_Backend_Range_Iterator<Tag_Index_Local, Uint32_Index, std::_Rb_tree_const_iterator<Tag_Index_Local> >::search_next_index()
+   0.21%  osm3s_query  libstdc++.so.6.0.19  [.] char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag)
+   0.21%  osm3s_query  osm3s_query          [.] Block_Backend_Range_Iterator<Uint32_Index, Node_Skeleton, std::_Rb_tree_const_iterator<std::pair<Uint32_Index, Uint32_Index> > >::search_next_index()
+   0.18%  osm3s_query  osm3s_query          [.] Tag_Index_Local::Tag_Index_Local(void*)
+   0.16%  osm3s_query  osm3s_query          [.] File_Blocks_Range_Iterator<Tag_Index_Local, Default_Range_Iterator<Tag_Index_Local> >::find_next_block()
+   0.14%  osm3s_query  osm3s_query          [.] make_geometry(Way_Skeleton const&, std::vector<Node, std::allocator<Node> > const&)
+   0.13%  osm3s_query  [kernel.kallsyms]    [k] find_get_page
+   0.12%  osm3s_query  libstdc++.so.6.0.19  [.] std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)
 ```

**Comment by mmd-osm** [comment]
Full run doesn't finish in a 24h time frame anymore. This looks like a serious regression.

After 23h54m43s: in "recurse", part 0, on line 255. Stack: 0 of 0 2022170 of 0 0 of 0
After 23h54m58s: in "make-area", part 0, on line 257. Stack: 0 of 0 2022792 of 0
After 23h55m13s: in "recurse", part 0, on line 255. Stack: 0 of 0 2023389 of 0 0 of 0
After 23h55m28s: in "recurse", part 0, on line 255. Stack: 0 of 0 2024085 of 0 0 of 0
After 23h55m43s: in "recurse", part 0, on line 255. Stack: 0 of 0 2024719 of 0 0 of 0
After 23h55m58s: in "recurse", part 0, on line 255. Stack: 0 of 0 2025268 of 0 0 of 0
After 23h56m13s: in "recurse", part 0, on line 255. Stack: 0 of 0 2025807 of 0 0 of 0
After 23h56m28s: in "make-area", part 0, on line 257. Stack: 0 of 0 2026376 of 0
After 23h56m43s: in "recurse", part 0, on line 255. Stack: 0 of 0 2027000 of 0 0 of 0
After 23h56m58s: in "recurse", part 0, on line 255. Stack: 0 of 0 2027651 of 0 0 of 0
After 23h57m15s: in "recurse", part 0, on line 255. Stack: 0 of 0 2028180 of 0 0 of 0
After 23h57m30s: in "recurse", part 0, on line 255. Stack: 0 of 0 2028683 of 0 0 of 0
After 23h57m45s: in "recurse", part 0, on line 255. Stack: 0 of 0 2029259 of 0 0 of 0
After 23h58m0s: in "recurse", part 0, on line 255. Stack: 0 of 0 2029903 of 0 0 of 0
After 23h58m15s: in "recurse", part 0, on line 255. Stack: 0 of 0 2030368 of 0 0 of 0
After 23h58m30s: in "recurse", part 0, on line 255. Stack: 0 of 0 2030926 of 0 0 of 0
After 23h58m45s: in "recurse", part 0, on line 255. Stack: 0 of 0 2031451 of 0 0 of 0
After 23h59m0s: in "recurse", part 0, on line 255. Stack: 0 of 0 2032047 of 0 0 of 0
After 23h59m15s: in "recurse", part 0, on line 255. Stack: 0 of 0 2032598 of 0 0 of 0
After 23h59m30s: in "recurse", part 0, on line 255. Stack: 0 of 0 2033269 of 0 0 of 0
After 23h59m45s: in "recurse", part 0, on line 255. Stack: 0 of 0 2033926 of 0 0 of 0
After 24h0m0s: in "recurse", part 0, on line 255. Stack: 0 of 0 2034515 of 0 0 of 0
After 24h0m1s: in "recurse", part 0, on line 255. Stack: 0 of 0 2034557 of 0 0 of 0

</osm>
runtime error: Query timed out in "recurse" at line 255 after 86401 seconds.

**Comment by drolbr** [comment]
Actually, this is a symptom of a semantic change: foreach now unions the content of the input set at all the loop runs. This is useful to collect e.g. derived objects and in line with the semantics for the new "complete".
However, we need to explicitly clear the set before the end of the loop to avoid collecting literally all border nodes in the world. Solutions could be to integrate that in "make-area", implement an explicit "clear" statement, modify the rules file, or a combination of those measures.

**Comment by mmd-osm** [comment]
Retest was successful, area creation is in the 19h range again on dev.
