### ISSUE TITLE
Disable all restrictions

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#447]
hey,
We're running our own server and are doing many small queries in parallel. We started to get errors now for what should be pretty easy:

```
StatusCodeError: 429 - 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"
    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
 <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">
<head>
  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" lang=\"en\"/>
  <title>OSM3S Response</title>
 </head>
<body>

<p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
<p><strong style=\"color:#FF0000\">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.54_osm_base Dispatcher_Client::request_read_and_idx::rate_limited. Please check /api/status for the quota of your IP address.
 </p>

 </body>
</html>
"
 at new StatusCodeError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1081:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1001:12)
```

So is there any way to completely disable this?

Cheers,
Daniel

**Comment by mmd-osm** [comment]
Either dispatcher and/or osm3s_query needs to be calles with `--rate-limit=0`

**Comment by gerbsen** [comment]
I've started the dispatcher now with:

`$BINDIR/dispatcher --osm-base --db-dir=$DBDIR --rate-limit=0 &`

But this still results in `Success /osm3s_v0.7.54_osm_base Dispatcher_Client::request_read_and_idx::rate_limited. Please check /api/status for the quota of your IP address.` For [osm3s_query.cc](https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/dispatch/osm3s_query.cc) I don't see any option to set `rate_limit`.

**Comment by mmd-osm** [comment]
Can you post http:// ... /api/status output?

**Comment by gerbsen** [comment]
```root@83981c5b3683:/# /Overpass-API/bin/dispatcher --my-status
Connected as: 0
Current time: 2017-11-15T09:09:10Z
Rate limit: 0
Currently running queries (pid, space limit, time limit, start time):
```

**Comment by mmd-osm** [comment]
ok, so rate limiting is disabled, but you're still getting those error messags. Which exact version are you running right now? 0.7.54.xx ?

**Comment by gerbsen** [comment]
`https://dev.overpass-api.de/releases/osm-3s_v0.7.54.10.tar.gz`

**Comment by gerbsen** [comment]
No, I disabled areas completely.

**Comment by gerbsen** [comment]
We did use the wrong service url :(
